### ISSUE TITLE
Add longpress detection feature

### ISSUE THREAD

**Issue by Reflex-Gravity** [jamiebuilds/tinykeys#103]
Can we add a long-press detection feature? Not sure if we can implement this using the current library.

I'm happy to help contribute to this feature.

**Comment by jamiebuilds** [comment]
No I suspect you could not find a way to make that work using this library.


For the purposes of discussing this, let's say the syntax for long press is:

```sh
# syntax
Long(Press)

# valid examples
Long(M)         # long press 'M'
Long(Shift+M)   # long press 'Shift + M'
Long(M) Long(N) # long press 'M' then long press 'N'

# invalid examples
Long(M N)       # invalid, use `Long(M) Long(N)`
```

Using that syntax, what are some examples of keybindings you'd create?

**Comment by Reflex-Gravity** [comment]
May be the below one too?

```shell
   # Key sequence
   Ctrl M Long(N)    # press ctrl, press M, long-press N
```

**Comment by jamiebuilds** [comment]
Right but what is an example of a keybinding you'd like to create?

**Comment by Reflex-Gravity** [comment]
Okay, you mean use-case?
Let's say I want to show available shortcuts in the application while holding `Alt`.

**Comment by jamiebuilds** [comment]
Playing with this idea more, I think it'd add a lot of complexity to this library. Unless there's a big use case for key sequences containing long presses, I think you'd be better off using your own function like this:

```js
function subscribeToLongPress(target, key, onLongPress) {
  let timer = null

  function onKeyDown(event) {
    if (event.key === key && timer == null) {
      timer = setTimeout(() => {
        timer = null
        onLongPress(event)
      }, 300)
    }
  }

  function onKeyUp(event) {
    if (event.key === key && timer != null) {
      clearTimeout(timer)
      timer = null
    }
  }

  target.addEventListener("keydown", onKeyDown)
  target.addEventListener("keyup", onKeyUp)
  
  return () => {
    target.removeEventListener("keydown", onKeyDown)
    target.removeEventListener("keyup", onKeyUp)
  }
}

let unsubscribe = subscribeToLongPress(window, "Alt", event => {
  console.log(event.key)
})
```

**Comment by mydudechris** [comment]
Would the above work for something like holding the spacebar down to drag a canvas around?
