### ISSUE TITLE
Multiple key sequence binding

### ISSUE THREAD

**Issue by www-chique** [jamiebuilds/tinykeys#115]
Hi! Absolutely love tinykeys.
I was wondering if there's a possibility to bind multiple shortcuts to the same function.
I would like the same function to be triggered if any of the sequences match.

So instead of writing
```
tinykeys(window, {
	"ArrowUp": (e) => {
		e.preventDefault();
		e.stopPropagation();
		//Do something here
	},
	"Equal": () => {
		e.preventDefault();
		e.stopPropagation();
		//Do something here
	},
	"Home": () => {
		e.preventDefault();
		e.stopPropagation();
		//Do something here
	},
});
```

I could do instead
```
tinykeys(window, {
	"ArrowUp, Equal, Home": () => {
		e.preventDefault();
		e.stopPropagation();
		//Do something here if either of ArrowUp, Equal or Home key were pressed
	},
});
```

**Comment by jamiebuilds** [comment]
Could you just pull the function out and share it?

```js
function onAction(e) {
  e.preventDefault();
  e.stopPropagation();
  //Do something here
}

tinykeys(window, {
	"ArrowUp": onAction,
	"Equal": onAction,
	"Home": onAction,
});
```

**Comment by www-chique** [comment]
For sure, that works just fine.
Was wondering if the suggestion would make it more elegant. But I guess that introduces unwanted complexity to the code.
Never mind, I'll just follow your solution.

Many thanks for the awesome work.
