### ISSUE TITLE
[Proposal] Add ability to define multiple shortcuts for one function

### ISSUE THREAD

**Issue by lesha1201** [jamiebuilds/tinykeys#128]
Currently we can only define one shortcut per function. It would be convenient to have ability to define multiple.

API can be like this:

```js
tinykeys(window, {
  "Shift+D": () => {
    alert("One shortcut")
  },
 "$mod+D, Alt+D": () => {
    alert("Multiple shortcuts")
  },
})
```

**Comment by jamiebuilds** [comment]
Just reference the same function

```js
function one() { alert("One shortcut") }
function two() { alert("Multiple shortcuts") }

tinykeys(window, {
  "Shift+D": one,
  "$mod+D": two,
  "Alt+D": two,
})
```

**Comment by Andrioden** [comment]
Any chance this could be reconsidered? It saves us the users for some code, and makes tinykeys interface even neater.

I agree to the suggest api above, using comma as separator.
