### ISSUE TITLE
ability to create handler without adding event listener

### ISSUE THREAD

**Issue by WickyNilliams** [jamiebuilds/tinykeys#132]
In some cases, it is useful to just have access to the handler _without_ it being registered as a listener. One use case is where you do not yet have access to the element instance, but wish to eagerly create a handler. 

Something like:

```ts
import { createListener } from "tinykeys";

const handler = createListener(shortcuts)

// later
someElement.addEventListener("keydown", handler)
```

Is this something you would support being added? Happy to make a PR if so

**Comment by jamiebuilds** [comment]
What do you mean by eagerly create the handler? I don't think it should be terribly expensive to run the function when you need to, the only real expense is parsing the keybindings, and that's pretty trivial to parse.

**Comment by WickyNilliams** [comment]
I mean I want to create a handler but register it later, separately. Rather than due to any performance implication. 

My use case specifically is in a web component where I don't have access to the element instance I want to listen to immediately, and want to attach it as a listener declaratively in render. Eg

```ts
class MyComponent extends LitElement {
  handleShortcuts = createListener({
    // shortcuts here
  })

  render() {
    return html`
      <div>
        <input @keydown=${this.handleShortcuts} />
      </div>
    `
  } 
}
```

I could of course attach the listener imperatively in a lifecycle hook after initial render (when the instance is actually available) , but I'd prefer to do it declaratively as above.

Does that make sense? It could be supported very easily without really affecting bundle size, and would not be a breaking change

**Comment by jamiebuilds** [comment]
Okay yeah, I see the point. If you want to create a PR that adds a `createKeybindingsHandler` function that pulls everything but the `addEventListener/removeEventListener` out and returns the `onKeyDown` handler (probably rename it to just `handler`), you can have the `keybindings` function just call out to it.

**Comment by WickyNilliams** [comment]
Cool yeah, that's what I was thinking. I'm away for a few days so will pick it up Monday
