### ISSUE TITLE
Expose the parse method

### ISSUE THREAD

**Issue by itaditya** [jamiebuilds/tinykeys#142]
Often times, the keyboard shortcut assigned to a handler also needs to be displayed within the UI like `CMD` + `Shift` + `g` instead of just a plain string. For that we need to convert the shortcut string into a data structure. We also need to convert `$mod` into `CMD` vs `Ctrl` based on platform. 

## Possible Solutions-
1. The `parse` method that is being used internally is almost doing the same thing. If it's exported and documented then people can import it in their application.
2. The `createKeybindingsHandler` function can be configured to return a tuple where first item is the event handler and second argument is the parsed shortcuts.

I can raise a PR if the maintainers like this proposal.

**Comment by jamiebuilds** [comment]
Sure, I like the first solution of exporting it. Can you just name it `parseKeybinding`?

**Comment by itaditya** [comment]
@jamiebuilds have raised a PR https://github.com/jamiebuilds/tinykeys/pull/144

**Comment by itaditya** [comment]
Hey @jamiebuilds, just wanted to get a sense of when this change will be released. (absolutely no rush though 😅)

**Comment by jamiebuilds** [comment]
Oh sorry I totally forgot

**Comment by jamiebuilds** [comment]
Published

**Comment by itaditya** [comment]
awesome, thanks ❤️
