### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by alexnm** [jamiebuilds/tinykeys#15]
Hey

I noticed this when loading the library on the server, the navigator object does not exist and causes a crash when building the pages for projects like next/nuxt that have out of the box server rendering.

Codesandbox: https://codesandbox.io/s/lingering-dawn-v88hi?file=/pages/index.js (the library is imported in index.js

I managed to bypass this by lazy loading it on the client, but probably more people will get into the same issue. I'm wondering if it makes sense for the library to ignore the server environment with a check for window or navigator.

sidenote: really nice library, I've been looking for something like this for a while.

**Comment by jamiebuilds** [comment]
Moving to #16
