### ISSUE TITLE
How to use this in angular? 

### ISSUE THREAD

**Issue by KaranTrivedi** [jamiebuilds/tinykeys#154]
Would it be possible to show an angular snippet? I feel very lost translating pure Java libs into angular components..

Thanks.

**Comment by jamiebuilds** [comment]
I don't really know how modern Angular code looks, but this library is framework-independent, and should be able to follow whatever pattern the framework uses to create subscriptions.

Looks like Angular has something like this:

```ts
// ...
  ngOnInit() {
    this.ngZone.runOutsideAngular(() => {
      this.unlisten = tinykeys(window, {
        // ...
      });
    });
  }

  ngOnDestroy() {
    this.unlisten();
  }
// ...
```

There's also something called [`HostListener`](https://angular.io/api/core/HostListener). You might be able to use that with `createKeybindingsHandler`

```ts
import { createKeybindingsHandler } from "tinykeys"
```
