### ISSUE TITLE
navigator.platform "deprecated"

### ISSUE THREAD

**Issue by kid-icarus** [jamiebuilds/tinykeys#184]
Just wondering what your thoughts are [platform being deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform) despite the fact that it's still supported everywhere.

I was having an internal debate about detecting which key is effectively `Mod`, and noticed you use `navigator.platform` [to do just that](https://github.com/jamiebuilds/tinykeys/blob/main/src/tinykeys.ts#L52-L56).

Feel free to close, I just wanted to see if you were considering an alternative, as user agent parsing heuristics are bloated at best.

**Comment by jamiebuilds** [comment]
Someday we'll be able to use [`navigator.userAgentData.platform`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/platform) but I doubt `navigator.platform` can ever actually be removed from the web, it may just become less useful with time (if new platforms start filling it with garbage or something).
