### ISSUE TITLE
How createKeybindingsHandler listens for any key?

### ISSUE THREAD

**Issue by Jarvie789** [jamiebuilds/tinykeys#187]
```js
  const handleK = createKeybindingsHandler({
    "*": () => {
      console.log('call');
    }
  });
```

**Comment by jamiebuilds** [comment]
I'm not sure why it would be desirable to do that with tinykeys. 

That's just the same as writing:

```ts
window.addEventListener("keydown", () => {...})
```

**Comment by Jarvie789** [comment]
> I'm not sure why it would be desirable to do that with tinykeys.
> 
> That's just the same as writing:
> 
> ```ts
> window.addEventListener("keydown", () => {...})
> ```

All right, thank you.
