### ISSUE TITLE
tinykeys cannot work

### ISSUE THREAD

**Issue by QC2168** [jamiebuilds/tinykeys#189]
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/tinykeys.js?v=88983d99' does not provide an export named 'default' (at useKeyboardShortcuts.ts:1:8)
```ts
import tinykeys from "tinykeys"

import { onMounted } from "vue"

export default function useKeyboardShortcuts() {
  onMounted(() => {
    tinykeys(window, {
      "Escape": () => {
        console.log("The 'Shift' and 'd' keys were pressed at the same time")
      }
    })
  })
}
```
```yaml
tinykeys:
  specifier: ^2.1.0
  version: 2.1.0
```

**Comment by QC2168** [comment]
but, I using `createKeybindingsHandler` function, it working

**Comment by marcuslindblom** [comment]
The import should be `import { tinykeys } from 'tinykeys'` because it's a named import

**Comment by aleksaKis** [comment]
They should update the docs with the @marcuslindblom example

**Comment by wobsoriano** [comment]
FYI if you're using Vue - https://github.com/wobsoriano/vue-tinykeys

**Comment by jamiebuilds** [comment]
Docs have been updated
