### ISSUE TITLE
How do i achieve Ctrl + +

### ISSUE THREAD

**Issue by wangguangyou** [jamiebuilds/tinykeys#19]
How do i achieve Ctrl + +

**Comment by jamiebuilds** [comment]
For future reference, **on a US keyboard** you'd want to write:

```js
"Control + Equal"
// or
"$mod + Equal" // (for Apple compatibility)
```

Because `+` is on the `=` key.

Although, keep in mind it may be something else on a [different keyboard](https://en.wikipedia.org/wiki/Keyboard_layout).
