### ISSUE TITLE
Meta vs Cmd

### ISSUE THREAD

**Issue by franky47** [jamiebuilds/tinykeys#2]
On Apple keyboards, the ⌘ key is labelled "cmd" for Command. Meta is more often found on Linux.

It could reduce confusion for Apple keyboard users to accept Cmd as a modifier, and include it in `$mod`.

![Image of an Apple US keyboard](https://i.stack.imgur.com/j4xYE.jpg)

**Comment by jamiebuilds** [comment]
The `KeyboardEvent.code` name for “Command” is `Meta`

**Comment by alcesleo** [comment]
As a Mac user this confused me too and I was about to open the same issue. Not saying you are wrong by sticking to the KeyboardEvent.code, but I've never heard a Mac-user refer to it as Meta.

**Comment by jamiebuilds** [comment]
I added a table to the readme for commonly used keys and codes https://github.com/jamiebuilds/tinykeys#commonly-used-keys-and-codes
