### ISSUE TITLE
Shift doesn't work when not using it as modifier

### ISSUE THREAD

**Issue by sandervspl** [jamiebuilds/tinykeys#20]
I need to use the `Shift` key as a key press without it being a modifier for another key. This does not work.

```
tinykeys(window, {
    'Shift': () => { ... }
})
```

Nothing happens.

**Comment by jamiebuilds** [comment]
I originally abandoned this in order to simplify the code that exists in other libraries, but I think I found a solution that keeps the size small... will update

**Comment by jamiebuilds** [comment]
published as v1.1.0
