### ISSUE TITLE
Method Map.prototype.clear called on incompatible receiver #<Window>

### ISSUE THREAD

**Issue by pnfcre** [jamiebuilds/tinykeys#3]
Hi there,

Great library! I however encounter the error `Method Map.prototype.clear called on incompatible receiver #<Window>`, here's a minimal reproduction sandbox: https://codesandbox.io/s/heuristic-wilbur-jz3iz?file=/src/index.ts. Thanks!

Kind regards,
Hampus Kraft.

**Comment by jamiebuilds** [comment]
Whoops yeah, it’s this right here, it either needs to be bound to the correct value or have a function wrap it

https://github.com/jamiebuilds/tinykeys/blob/300598b02b0e29c5f5022e4086530a80afdf3e7d/src/tinykeys.ts#L141

**Comment by jamiebuilds** [comment]
fixed
