### ISSUE TITLE
How can I trigger the different key combinations within a test?

### ISSUE THREAD

**Issue by jsanes** [jamiebuilds/tinykeys#33]
First of all, congratulations on TinyKeys. It has been very helpful.

Now I need to write the tests of my application that's using the package and haven't been able to cover the code triggered by the shortcuts. How can I get that done?

I'm using Jest, Enzyme and Chai in my tests.

Thank you very much.

**Comment by jamiebuilds** [comment]
Just call the code directly?

```js
import tinykeys from "tinykeys"

export function _onCombo() {
  // ...
}

tinykeys({
  "C O M B O": _onCombo,
})
```

```js
import test from "test"
import { _onCombo } from "./src"

test("C O M B O", t => {
  _onCombo()
})
```

**Comment by jsanes** [comment]
Will try it that way, Thanks!
