### ISSUE TITLE
Uncaught TypeError: t.getModifierState is not a function

### ISSUE THREAD

**Issue by tomcon** [jamiebuilds/tinykeys#40]
tinykeys@1.0.4
Chrome Version 85.0.4183.121 (Official Build) (64-bit)

```
var e = ["Shift", "Meta", "Alt", "Control"]
  , t = /Mac|iPod|iPhone|iPad/.test(navigator.platform) ? "Meta" : "Control";

// error thrown here:
t.getModifierState(t.key) || 
```
navigator.platform = "Win32"
t = "Control"

**Comment by jamiebuilds** [comment]
That's... weird. I have an [explicit check](https://github.com/jamiebuilds/tinykeys/blob/main/src/tinykeys.ts#L115-L120) for `KeyboardEvent` and according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState#Browser_compatibility) Chrome 85 should support `KeyboardEvent.getModifierState()`. Does it only happen with the `Control` key?

**Comment by tomcon** [comment]
sorry for the delay @jamiebuilds, the error msg occurs at startup:

```
  setupKeyboardShortcuts() {
    tinykeys( window, {
      'F5': (event) => { event.preventDefault(); this.showFrontDesk(); },
      'F6': (event) => { event.preventDefault(); this.showFinder(); },
      'F7': (event) => { event.preventDefault(); this.showTodoMan(); },
      'F8': (event) => { event.preventDefault(); this.showMessageMan(); },
      'F9': (event) => { event.preventDefault(); this.showListManager(); },
      'F10': (event) => { event.preventDefault(); this.store.toggleTalking(); },
    })
  }  
```
