### ISSUE TITLE
lookbehind assertion regex added in 1.1.2 breaks on safari

### ISSUE THREAD

**Issue by intabulas** [jamiebuilds/tinykeys#85]
In 1.1.2 (commit 9154e4) the change to split on a regex uses a lookbehind assertion ?<! and this totally breaks on safari with a "Invalid regular expression: invalid group specifier name" error. Safari currently does not support lookbehind assertions. 

For now I have rolled back to 1.1.1

ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#browser_compatibility

**Comment by tcneuen** [comment]
Has the same issue with Firefox 76

**Comment by jamiebuilds** [comment]
Fixed, apologies
