### ISSUE TITLE
HELP: debounce keypress

### ISSUE THREAD

**Issue by cpvalente** [jamiebuilds/tinykeys#99]
Hi,
I was wondering if there are any plans on integrating debounce into the library? 
or otherwise would you have recommendations on how to achieve this in some key combinations?

**Comment by jamiebuilds** [comment]
Can you explain in detail the behavior you want?

**Comment by cpvalente** [comment]
Sure.
I have used tiny keys in a react app to handle CRUD operations in a table.

I would like to have a possibility to define a debounce time after a user triggers a shortcut, that disables - ideally some, but maybe all - listeners.

I would use this to ensure that shortcuts cannot be called in series (ie: save)

Hopefully this was clear

**Comment by jamiebuilds** [comment]
You can likely just do that on your own without any changes to this library.

If you want to debounce a single callback on its own:

```js
function debounce(func, ms) {
  let timer
  return (...args) => {
    clearTimeout(timer)
    timer = setTimeout(() => {
      func(...args)
    }, ms)
  }
}

tinykeys(window, {
  "$mod+S": debounce(() => {
    save()
  }),
})
```

If you want to debounce many callbacks using a single timer:

```js
function createDebounceGroup(ms) {
  let timer
  return {
    debounce(func) {
      return (...args) => {
        clearTimeout(timer)
        timer = setTimeout(() => {
          func(...args)
        }, ms)
      }
    }
  }
}

const debounceGroup = createDebounceGroup(300)

tinykeys(window, {
  "$mod+S": debounceGroup.debounce(() => {
    save()
  }),
  "$mod+Shift+S": debounceGroup.debounce(() => {
    saveAs()
  })
})
```

Warning: I haven't tested if that code works at all, you might have to fix some mistakes, or you might just want to find a library with a debounce function that does what you want.

**Comment by cpvalente** [comment]
Thank you, I realise that debouncing in javascript(?) doesnt share other than the name from hardware debouncing.
I guess what I am looking for is a way to throttle a function, ie: stop it from being called too many times from a stuck finger situation.

There is plenty of code out there and I am sure I will figure it out, hopefully wont need to migrate into another library

**Comment by jamiebuilds** [comment]
throttling and debouncing are two similar but slightly different functions, and there are several different kinds of "throttles" that you'll have to figure out which you want. Here's one though:

```js
function throttle(func, ms) {
  let throttling = false
  return (...args) => {
    if (!throttling) {
      func(...args)
      throttling = true
      setTimeout(() => {
        throttling = false
      }, ms)
    }
  }
}

tinykeys(window, {
  "$mod+S": throttle(() => {
    save()
  }, 300),
})
```

This will call the `save()` function immediately, but then will wait `300` ms before allowing it to be called again.

If that's not exactly what you want, I'd recommend using Lodash's `lodash.throttle` package https://www.npmjs.com/package/lodash.throttle
